geodjango/geodjango/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

objects/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('workshops', views.workshops, name='workshops'),
    path("accounts/", include("django.contrib.auth.urls")),
    #Workshops
    path('export/sammanfattning/', views.export_csv, name='csv_sammanfattning'),
    path('export/platser/', views.export_objects_csv, name='csv_sammanfattning'),
    path('workshop1B/', views.workshop1B, name='workshop1B'),
    path('workshop1C/', views.workshop1C, name='workshop1C'),
    path('workshop2/', views.workshop2, name='workshop2'),
    path('workshop3/', views.workshop3, name='workshop3'),
    #Strategy
    path('karta/', views.map, name='karta'),
    path('platser/', views.allaplatser, name='karta'),
    path('platser/malmo', views.allaplatser, name='karta'),
    path('platser/marginal', views.allaplatser_margin, name='karta'),
    path('platser/atgard', views.allaplatser_atgard, name='karta'),
    path('handlingar/', views.handlingar, name='handlingar'),
    path('handelser/', views.strategi, name='handelser'),
    path('pathway/<int:pathway_id>', views.pathway, name='pathway'),
    path('pathway/', views.pathway, name='pathway'),
    path('export/', views.export, name='export'),
    # See specific things
    path('event/<int:event_id>/', views.event, name='event'),
    path('plats/<int:object_id>/', views.object, name='object'),
    path('pathways/<int:object_id>/', views.paths, name='paths'),
    path('pathways/<int:object_id>/<int:pathway_id>', views.paths, name='paths'),
    path('kriterium/<int:criteria_id>/', views.criteria, name='criteria'),
    path('atgard/<int:measure_id>/', views.measure, name='measure'),
    # New things
    path('nytt_objekt/<int:event_id>/', views.new_object, name='new_object'),
    path('ny_atgard/', views.new_measure, name='new_measure'),
    path('atgarder/', views.new_measure, name='new_measure'),
    # Edit things
    path('edit/information/', views.workshop1A, name='workshop1A'),
    path('edit/event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('edit/kriteria/<int:criteria_id>/', views.edit_criteria, name='edit_criteria'),
    path('edit/plats/<int:object_id>/', views.edit_object, name='edit_object'),
    path('edit/measure/<int:measure_id>/', views.edit_measure, name='edit_measure'),
    path('fokus/', views.edit_goal, name='edit_goal'),
    path('edit/niva/', views.edit_level, name='edit_level'),
    path('edit/omrade', views.edit_omrade, name='edit_omrade'),
    path('edit/tider', views.edit_times, name='edit_times'),
    # Remove things
    path('tabort/kriteria/<int:criteria_id>/', views.delete_criteria, name='delete_criteria'),
    path('tabort/event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('tabort/plats/<int:object_id>/', views.delete_object, name='delete_object'),
    path('tabort/measure/<int:measure_id>/', views.delete_measure, name='delete_measure'),
    path('tabort/pathway/<int:pathway_id>/', views.delete_pathway, name='delete_pathway'),
    #
    path('connect/<int:measure_id>/<int:object_id>/', views.connect_measure, name='connect_measure'),
    path('remove/<int:measure_id>/<int:object_id>/', views.remove_measure, name='remove_measure'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

robusta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('objects.urls')),
    path('admin/', admin.site.urls),    
]

objects/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry
from django.contrib.auth.models import AbstractUser
from django.core import serializers
from django.shortcuts import get_object_or_404

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=200)
    focus = models.TextField(blank=True)
    location =  models.PointField(srid=4326, null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    followup = models.TextField(null=True,blank=True)
    area =  models.PolygonField(null=True,blank=True)
    level = models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    def __str__(self):
        return self.name
    def get_location(self):
        return GEOSGeometry(self.area).json

class CustomUser(AbstractUser):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    def __str__(self):
        return self.username

class Criteria(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

MALMO = [(1,"1/1"),(2,"1/2"),(5,"1/5"),(10,"1/10"),(20,"1/20"),(50,"1/50"),(100,"1/100"),(200,"1/200"),(500,"1/500"),(1000, "1/1000"),(10000, "1/10000"),(100000,"1/100000"),(1000000,"1/1000000")]

class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    returntime = models.IntegerField(blank=True, null=True, choices=MALMO)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    criteria =  models.ForeignKey(Criteria, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Object(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    location =  models.GeometryField()
    altitude = models.DecimalField(max_digits=5,decimal_places=2)
    marginal = models.DecimalField(max_digits=5,decimal_places=2,null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def get_location(self):
        return GEOSGeometry(self.location).json
    def needs_own(self):
        n = self.measure_set.count()
        if n == 0:
            return 2
        m = self.measure_set.filter(general=False).count()
        if m >= 1:
            return 1
        else:
            return 0
    def get_margin(self):
        # Get Malmö for the event
        malmo = self.event.returntime
        returntimes = get_object_or_404(Returntimes, city=self.city.id)
        # Get the relevant returntime based on malmö
        if malmo:
            returntime = getattr(returntimes, 'y'+str(malmo))
        else:
            returntime = 0
        # Calculate margin
        margin = self.altitude - returntime
        return margin
    class Meta:
        db_table = "objects_object2"

class Measure(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    cost = models.IntegerField()
    level = models.DecimalField(max_digits=5,decimal_places=2)
    general = models.BooleanField()
    object = models.ManyToManyField(Object)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Pathway(models.Model):
    steg1 = models.ForeignKey(Measure, related_name='measure1', verbose_name="Första åtgärd",unique=False,on_delete=models.RESTRICT)
    steg2 = models.ForeignKey(Measure, related_name='measure2', verbose_name="Andra åtgärd",unique=False,blank=True,null=True,on_delete=models.RESTRICT)
    steg3 = models.ForeignKey(Measure, related_name='measure3', verbose_name="Tredje åtgärd",unique=False,blank=True,null=True,on_delete=models.RESTRICT)
    description = models.TextField(blank=True,null=True)
    cost = models.IntegerField(blank=True,null=True)
    level = models.DecimalField(max_digits=5,decimal_places=2)
    object = models.ForeignKey(Object,on_delete=models.RESTRICT,null=True)
    city = models.ForeignKey(City,on_delete=models.RESTRICT)
    user = models.ForeignKey(CustomUser,on_delete=models.RESTRICT)
    def __str__(self):
        return str(self.id)

class Returntimes(models.Model):
    city = models.ForeignKey(City,on_delete=models.RESTRICT)
    y1 = models.DecimalField(max_digits=5,decimal_places=2)
    y2 = models.DecimalField(max_digits=5,decimal_places=2)
    y5 = models.DecimalField(max_digits=5,decimal_places=2)
    y10 = models.DecimalField(max_digits=5,decimal_places=2)
    y20 = models.DecimalField(max_digits=5,decimal_places=2)
    y50 = models.DecimalField(max_digits=5,decimal_places=2)
    y100 = models.DecimalField(max_digits=5,decimal_places=2)
    y200 = models.DecimalField(max_digits=5,decimal_places=2)
    y500 = models.DecimalField(max_digits=5,decimal_places=2)
    y1000 = models.DecimalField(max_digits=5,decimal_places=2)
    y10000 = models.DecimalField(max_digits=5,decimal_places=2)
    y100000 = models.DecimalField(max_digits=5,decimal_places=2)
    y1000000 = models.DecimalField(max_digits=5,decimal_places=2)
    description = models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.id)

objects/templates/objects/all.html
{% extends 'base.html' %}
{% block header %}
  {% load leaflet_tags %}
  {% leaflet_css %}
  {% leaflet_js %}
{% endblock %}

{% block content %}

<div class="columns">
  <div class="column is-one-quarter">
    <div class="box">
        <h2 class="title is-2">Sårbara platser</h2>
        <div class="columns">
          <div class="column is-one-third">
            <p>TOTAL<br/>&nbsp;</p>
            <h2 class="title is-3">{{ total }}</h2>
          </div>
          <div class="column is-one-third">
            <p>UTAN MARGINAL</p>
            <h2 class="title is-3 has-text-danger">{{ akut }}</h2>
          </div>
          <div class="column is-one-third">
            <p>UTAN ÅTGÄRD</p>
            <h2 class="title is-3 has-text-warning">{{ utan }}</h2>
          </div>
        </div>
        <a href="malmo"><button class="button is-medium is-link is-info"><i class="fa-solid fa-sort"></i>&nbsp; MALMÖ</button></a><br/><br/>
        <a href="marginal"><button class="button is-medium is-link is-info"><i class="fa-solid fa-sort"></i>&nbsp; Marginal</button></a><br/><br/>
        <a href="atgard"><button class="button is-medium is-link is-info"><i class="fa-solid fa-sort"></i>&nbsp; Åtgärder</button></a><br/>
    </div>
  </div>
  <div class="column">
        <div class="box">
    {% if allobjects.count != 0 %}
      {%for ob in allobjects%}
        <a href="/plats/{{ob.id}}">
          <div class="field is-grouped is-grouped-multiline" style="margin-bottom:0px;">

          <div class="control" >
            <div class="tags has-addons">
              <span class="tag" style="width:300px"><b>{{ob.name}}</b></span>
            </div>
          </div>

          <div class="control">
            <div class="tags has-addons">
              <span class="tag">MALMÖ: </span>
              {% if ob.malmo >= 1000 %}
                <span class="tag is-link" style="width:80px">1/{{ob.malmo}}</span>
                {% elif ob.malmo >= 100 %}
                  <span class="tag is-info" style="width:80px">1/{{ob.malmo}}</span>
                {% elif ob.malmo > 0 %}
                    <span class="tag is-primary" style="width:80px">1/{{ob.malmo}}</span>
                {% else %}
                <span class="tag" style="width:80px">Ej</span>

              {% endif %}
            </div>
          </div>

          <div class="control">
            <div class="tags has-addons">
              <span class="tag">Marginal:</span>
              {% if ob.margin <= 0 %}
                <span class="tag is-danger" style="width:60px">{{ob.margin}} m.</span>
              {% elif ob.margin <= 1 %}
                <span class="tag is-warning" style="width:60px">{{ob.margin}} m.</span>
              {% else %}
                <span class="tag is-success" style="width:60px">{{ob.margin}} m.</span>
              {% endif %}
            </div>
          </div>

          <div class="control">
            <div class="tags has-addons">
              {% if ob.need == 1 %}
                  <span class="tag is-warning">Egen åtgärd</span>
              {% endif %}
              {% if ob.need == 2 %}
                <span class="tag is-warning">Ingen åtgärd</span>
              {% endif %}
            </div>
          </div>

        </div>

                </a>
        {%endfor%}
      {% else %}
          <a href="/handelser"><div class="event_box">
        <p>Inga sårbara platser ännu. Lägg till sårbara platser i respektive oönskade händelse.</p>
        </div></a>

      {% endif %}
      </div>
  </div>

</div>

{% endblock %}

objects/templates/objects/measure.html
{% extends 'base.html' %}
{% block header %}
{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-one-third">
    <div class="box">
      <div class="block"><span class="tag">Åtgärd</span></div>
      <h2 class="title is-2">{{measure.name }}</h2>
      <p>{{measure.description}}</p>
      <div class="field is-grouped is-grouped-multiline">
        <div class="tags has-addons">
        <span class="tag is-info is-light is-large">Effektivt till:</span>
        <span class="tag is-info is-large">{{measure.level}} m.</span>
        </div>
      </div>
      <br/>
      <div class="field is-grouped is-grouped-multiline">
          <div class="tags has-addons">
          <span class="tag is-success is-light">Effektivt för:</span><br/>
          <span class="tag is-success">{{ allobjects|length }} st.</span>
          <span class="tag is-warning is-light">Ej effektivt för:</span><br/>
          <span class="tag is-warning">{{ no_objects|length }} st.</span>
          </div>
        </div>
        <br/>
      <div class="field is-grouped is-grouped-multiline">
        <div class="tags has-addons">
          <span class="tag is-info is-light">Platsspecifik:</span>
            {% if measure.general %}
              <span class="tag">NEJ</span>
            {% else %}
              <span class="tag">JA</span>
            {% endif %}
          </div>
        </div>
        <br/>
        <div class="field is-grouped is-grouped-multiline">
          <div class="tags has-addons">
              <span class="tag is-info is-light">Kostnadsuppskattning: </span>
              {% if measure.cost == 1 %}<span class="tag">Billigt</span> {%endif%}
              {% if measure.cost == 2 %}<span class="tag">Relativt Billigt</span> {%endif%}
              {% if measure.cost == 3 %}<span class="tag">Mellan</span> {%endif%}
              {% if measure.cost == 4 %}<span class="tag">Relativt Dyrt</span> {%endif%}
              {% if measure.cost == 5 %}<span class="tag">Dyrt</span> {%endif%}
        </div>
      </div>
      <br/>





        <br/><br/>
        <a href="/edit/measure/{{measure.id}}"><button class="button is-link is-rounded"><i class="fa-solid fa-pen"></i>&nbsp;Ändra</button></a><br/><br/>
    </div>
  </div>
  <div class="column">
    <div class="box">
              <h5 class="title is-5"><b>Effektiv för sårbara platser: </b></h5>
              {%for ob in allobjects%}
              <a href="/plats/{{ob.id}}">
                <div class="field is-grouped is-grouped-multiline" style="margin-bottom:0px;">

                <div class="control" >
                  <div class="tags has-addons">
                    <span class="tag" style="width:300px"><b>{{ob.name|truncatechars:50}}</b></span>
                  </div>
                </div>

                <div class="control">
                  <div class="tags has-addons">
                    <span class="tag">Marginal:</span>
                    {% if ob.margin <= 0 %}
                      <span class="tag is-danger" style="width:60px">{{ob.margin}} m.</span>
                    {% elif ob.margin <= 1 %}
                      <span class="tag is-warning" style="width:60px">{{ob.margin}} m.</span>
                    {% else %}
                      <span class="tag is-success" style="width:60px">{{ob.margin}} m.</span>
                    {% endif %}
                  </div>
                </div>

                <div class="control">
                  <div class="tags has-addons">
                    <span class="tag">Efter åtgärd :</span>
                    {% if ob.newmargin <= 0 %}
                      <span class="tag is-danger" style="width:60px">{{ob.newmargin}} m.</span>
                    {% else %}
                      <span class="tag is-success" style="width:60px">{{ob.newmargin}} m.</span>
                    {% endif %}
                  </div>
                </div>

              </div>
              {% endfor %}
    </div>
    <div class="box">
      <h5 class="title is-5"><b>Inte effektiv för sårbara platser: </b></h5>
              {%for ob in no_objects%}
              <a href="/plats/{{ob.id}}">
                <div class="field is-grouped is-grouped-multiline" style="margin-bottom:0px;">

                <div class="control" >
                  <div class="tags has-addons">
                    <span class="tag" style="width:300px"><b>{{ob.name|truncatechars:50}}</b></span>
                  </div>
                </div>

                <div class="control">
                  <div class="tags has-addons">
                    <span class="tag">Marginal:</span>
                    {% if ob.margin <= 0 %}
                      <span class="tag is-danger" style="width:60px">{{ob.margin}} m.</span>
                    {% elif ob.margin <= 1 %}
                      <span class="tag is-warning" style="width:60px">{{ob.margin}} m.</span>
                    {% else %}
                      <span class="tag is-success" style="width:60px">{{ob.margin}} m.</span>
                    {% endif %}
                  </div>
                </div>
              </div>
              {% endfor %}
    </div>
  </div>
</div>

{% endblock %}

objects/templates/objects/new_area.html
{% extends 'base.html' %}
{% block header %}
  {% load leaflet_tags %}
  {% leaflet_js plugins="forms" %}
  {% leaflet_css plugins="forms" %}
{% endblock %}

{% block content %}
<div class="columns">
  <div class="column is-one-quarter">
    <div class="box">
      <h2 class="title is-4">Ny yta</h2>
      <p>Område: <span class="tag is-info">{{ city.name }}</span></p>
      <p>Oönskade händelse: <span class="tag is-info">{{ event.name }}</span> </p>
    </div>
  </div>
  <div class="column">
    <div class="box">

      <div class="control">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button is-success is-fullwidth is-medium mt-5"
          type="submit">Spara
          </button>
    </form>
  </div>
</div>
</div>
</div>
<script type="text/javascript">
    window.addEventListener("map:init", function (e) {
        var detail = e.detail;
        detail.map.setView([{{city.location.y}},{{city.location.x}}], 16);
    }, false);

</script>
{% endblock %}

objects/templates/objects/pathways.html
{% extends 'base.html' %}
{% block header %}
  {% load leaflet_tags %}
  {% leaflet_css %}
  {% leaflet_js %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"></script>

{% endblock %}

{% block content %}
<div class="columns">
<div class="column is-one-third">
  <div class="box">
    <div class="block"><span class="tag">Sårbar plats</span></div>
    <h2 class="title is-2">{{object.name }}</h2>
    <p>{{object.description }}</p>
    <div class="columns">
      <div class="column is-one-third">
        <p>MALMÖ</p>
        {% if object.event.returntime %}
        <h2 class="title is-3">1/{{object.event.returntime }} <br/>år</h2>
        {% else %}
        <h2 class="title is-3">-</h2>
        {% endif %}
      </div>
      <div class="column is-one-third">
        <p>Möh</p>
        <h2 class="title is-3 has-text-info">{{object.altitude }} meter</h2>
      </div>
      <div class="column is-one-third">
        <p>MARGINAL</p>
          {% if object.get_margin > 0 %}
            <h2 class="title is-3 has-text-warning">{{ object.get_margin }} meter</h2>
          {% else %}
            <h2 class="title is-3 has-text-danger">{{ object.get_margin }} meter</h2>
          {% endif %}
      </div>
    </div>


    <p><b>Framgångskriteria:</b><span class="tag"><a href="/kriterium/{{object.event.criteria.id}}">{{object.event.criteria.name }}</a></span></p>
    <p><b>Oönskade händelse:</b><span class="tag"><a href="/event/{{object.event.id}}">{{object.event.name }}</a></span></p>
    <br/>
    <div class="block">
    {% leaflet_map "specialbigmap" callback="map_init" %}
    </div>
    <button class="button is-info is-rounded" onclick="edit()"><i class="fa-solid fa-pen"></i>&nbsp;Ändra</button>
    <button class="button is-primary is-rounded" onclick="ny()">Ändra åtgärder</button>
</div>
</div>

<div class="column">
  <div class="box">
    <h2 class="title is-4">Handlingsvägar</h2>

      {% autoescape off %}
      {{ plot_path }}
      {% endautoescape %}

      {%for path in object.pathway_set.all%}
        <div class="box">
        <span class="tag is-medium">{{ path.steg1.name }}</span>
        {%if path.steg2 %}
          > <span class="tag is-medium">{{ path.steg2.name }}</span>
        {%endif%}
        {%if path.steg3 %}
          > <span class="tag is-medium">{{ path.steg3.name }}</span>
        {%endif%}
        <br/>
        {{ path.description }}<br/>
        <i>Kostnad:</i> <span class="tag is-info">{{ path.steg1.cost }} {%if path.steg2%} > {{ path.steg2.cost }} {% endif %}{%if path.steg3%}> {{ path.steg3.cost }}{% endif %}</span>
        <i>Effektivt nivå:</i> <span class="tag is-info">{{ path.steg1.level }} {%if path.steg2%}> {{ path.steg2.level }} {% endif %}{%if path.steg3%}> {{ path.steg3.level }}{% endif %} </span>
        <p></p>
        <a href="/pathways/{{object.id}}/{{path.id}}"><button class="button is-small is-link is-rounded"">Ändra</button></a>
        <a href="/tabort/pathway/{{path.id}}"><button class="button is-small is-link is-rounded has-text-right">Ta bort</button></a>
        </div>
      {%endfor%}


    </div>
    <div class="box">
      {%if path%}
      <h2 class="title is-4">Editera handlingsväg</h2>
      {%else%}
      <h2 class="title is-4">Skapa handlingsväg</h2>
      {%endif%}

      <form method="POST">
      {% csrf_token %}
      <span class="tag">Åtgärd 1:</span> <div class="select">{{ form.steg1 }}</div><br/><br/>
      <span class="tag">Åtgärd 2:</span> <div class="select">{{ form.steg2 }}</div><br/><br/>
      <span class="tag">Åtgärd 3:</span> <div class="select">{{ form.steg3 }}</div><br/><br/>
      {{ form.description }}<br/>

      {%if path%}
        <button class="button is-info is-rounded" type="submit">Spara handlingsväg</button>
        <a href="/pathways/{{object.id}}"><button class="button is-link is-rounded"">Ångra</button></a>
      {%else%}
        <button class="button is-info is-rounded" type="submit">Skapa handlingsväg</button>
      {%endif%}

  </div>
</div>

</div>



<script type="text/javascript">

    function map_init(map, options) {
      var basemaps = {
          'Nu '       : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '10', format: 'image/png', transparent: true, opacity: 0.5}),
          '1 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '8', format: 'image/png', transparent: true, opacity: 0.5}),
          '1.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '7', format: 'image/png', transparent: true, opacity: 0.5}),
          '2 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '6', format: 'image/png', transparent: true, opacity: 0.5}),
          '2.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '5', format: 'image/png', transparent: true, opacity: 0.5}),
          '3 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '4', format: 'image/png', transparent: true, opacity: 0.5}),
          '3.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '3', format: 'image/png', transparent: true, opacity: 0.5}),
          '4 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '2', format: 'image/png', transparent: true, opacity: 0.5}),
          '4.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '1', format: 'image/png', transparent: true, opacity: 0.5}),
          '5 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '0', format: 'image/png', transparent: true, opacity: 0.5})
      }
      L.control.layers(basemaps).addTo(map);
        var group = new L.featureGroup();
        {% if object.location.y %}
          var mark = L.marker([{{ object.location.y }},{{ object.location.x }}]).addTo(map);
          group.addLayer(mark);
        {% else %}
          var jsonob = {% autoescape off %}{{ object.get_location }}{% endautoescape %};
          var latlngs = jsonob.coordinates[0];
          var reversed = []
          function reverseFunction(value, index, array) {
            reversed += array[index].reverse();
          }
          latlngs.forEach(reverseFunction);
          var polygon = L.polygon(latlngs, {color: 'red'}).addTo(map);
          group.addLayer(polygon);
        {% endif %}
        map.fitBounds(group.getBounds());
    }

   function edit() { window.location = '/edit/plats/{{object.id}}' };
   function ny() { window.location = '/plats/{{object.id}}/' };
  </script>


{% endblock %}