geodjango/geodjango/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

objects/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('workshops', views.workshops, name='workshops'),
    path("accounts/", include("django.contrib.auth.urls")),
    #Workshops
    path('export/sammanfattning/', views.export_csv, name='csv_sammanfattning'),
    path('export/platser/', views.export_objects_csv, name='csv_sammanfattning'),
    path('workshop1B/', views.workshop1B, name='workshop1B'),
    path('workshop1C/', views.workshop1C, name='workshop1C'),
    path('workshop2/', views.workshop2, name='workshop2'),
    path('workshop3/', views.workshop3, name='workshop3'),
    #Strategy
    path('karta/', views.map, name='karta'),
    path('platser/', views.allaplatser, name='karta'),
    path('platser/malmo', views.allaplatser, name='karta'),
    path('platser/marginal', views.allaplatser_margin, name='karta'),
    path('platser/atgard', views.allaplatser_atgard, name='karta'),
    path('handlingar/', views.handlingar, name='handlingar'),
    path('handelser/', views.strategi, name='handelser'),
    path('pathway/<int:pathway_id>', views.pathway, name='pathway'),
    path('pathway/', views.pathway, name='pathway'),
    path('export/', views.export, name='export'),
    # See specific things
    path('event/<int:event_id>/', views.event, name='event'),
    path('plats/<int:object_id>/', views.object, name='object'),
    path('pathways/<int:object_id>/', views.paths, name='paths'),
    path('pathways/<int:object_id>/<int:pathway_id>', views.paths, name='paths'),
    path('kriterium/<int:criteria_id>/', views.criteria, name='criteria'),
    path('atgard/<int:measure_id>/', views.measure, name='measure'),
    # New things
    path('nytt_objekt/<int:event_id>/', views.new_object, name='new_object'),
    path('ny_atgard/', views.new_measure, name='new_measure'),
    path('atgarder/', views.new_measure, name='new_measure'),
    # Edit things
    path('edit/information/', views.workshop1A, name='workshop1A'),
    path('edit/event/<int:event_id>/', views.edit_event, name='edit_event'),
    path('edit/kriteria/<int:criteria_id>/', views.edit_criteria, name='edit_criteria'),
    path('edit/plats/<int:object_id>/', views.edit_object, name='edit_object'),
    path('edit/measure/<int:measure_id>/', views.edit_measure, name='edit_measure'),
    path('fokus/', views.edit_goal, name='edit_goal'),
    path('edit/niva/', views.edit_level, name='edit_level'),
    path('edit/omrade', views.edit_omrade, name='edit_omrade'),
    path('edit/tider', views.edit_times, name='edit_times'),
    # Remove things
    path('tabort/kriteria/<int:criteria_id>/', views.delete_criteria, name='delete_criteria'),
    path('tabort/event/<int:event_id>/', views.delete_event, name='delete_event'),
    path('tabort/plats/<int:object_id>/', views.delete_object, name='delete_object'),
    path('tabort/measure/<int:measure_id>/', views.delete_measure, name='delete_measure'),
    path('tabort/pathway/<int:pathway_id>/', views.delete_pathway, name='delete_pathway'),
    #
    path('connect/<int:measure_id>/<int:object_id>/', views.connect_measure, name='connect_measure'),
    path('remove/<int:measure_id>/<int:object_id>/', views.remove_measure, name='remove_measure'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

robusta/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('objects.urls')),
    path('admin/', admin.site.urls),    
]

objects/models.py
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point, GEOSGeometry
from django.contrib.auth.models import AbstractUser
from django.core import serializers
from django.shortcuts import get_object_or_404

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=200)
    focus = models.TextField(blank=True)
    location =  models.PointField(srid=4326, null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    followup = models.TextField(null=True,blank=True)
    area =  models.PolygonField(null=True,blank=True)
    level = models.DecimalField(max_digits=5,decimal_places=2,null=True,blank=True)
    def __str__(self):
        return self.name
    def get_location(self):
        return GEOSGeometry(self.area).json

class CustomUser(AbstractUser):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    def __str__(self):
        return self.username

class Criteria(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

MALMO = [(1,"1/1"),(2,"1/2"),(5,"1/5"),(10,"1/10"),(20,"1/20"),(50,"1/50"),(100,"1/100"),(200,"1/200"),(500,"1/500"),(1000, "1/1000"),(10000, "1/10000"),(100000,"1/100000"),(1000000,"1/1000000")]

class Event(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    returntime = models.IntegerField(blank=True, null=True, choices=MALMO)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    criteria =  models.ForeignKey(Criteria, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Object(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    location =  models.GeometryField()
    altitude = models.DecimalField(max_digits=5,decimal_places=2)
    marginal = models.DecimalField(max_digits=5,decimal_places=2,null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def get_location(self):
        return GEOSGeometry(self.location).json
    def needs_own(self):
        n = self.measure_set.count()
        if n == 0:
            return 2
        m = self.measure_set.filter(general=False).count()
        if m >= 1:
            return 1
        else:
            return 0
    def get_margin(self):
        # Get Malmö for the event
        malmo = self.event.returntime
        returntimes = get_object_or_404(Returntimes, city=self.city.id)
        # Get the relevant returntime based on malmö
        if malmo:
            returntime = getattr(returntimes, 'y'+str(malmo))
        else:
            returntime = 0
        # Calculate margin
        margin = self.altitude - returntime
        return margin
    class Meta:
        db_table = "objects_object2"

class Measure(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    cost = models.IntegerField()
    level = models.DecimalField(max_digits=5,decimal_places=2)
    general = models.BooleanField()
    object = models.ManyToManyField(Object)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Pathway(models.Model):
    steg1 = models.ForeignKey(Measure, related_name='measure1', verbose_name="Första åtgärd",unique=False,on_delete=models.RESTRICT)
    steg2 = models.ForeignKey(Measure, related_name='measure2', verbose_name="Andra åtgärd",unique=False,blank=True,null=True,on_delete=models.RESTRICT)
    steg3 = models.ForeignKey(Measure, related_name='measure3', verbose_name="Tredje åtgärd",unique=False,blank=True,null=True,on_delete=models.RESTRICT)
    description = models.TextField(blank=True,null=True)
    cost = models.IntegerField(blank=True,null=True)
    level = models.DecimalField(max_digits=5,decimal_places=2)
    object = models.ForeignKey(Object,on_delete=models.RESTRICT,null=True)
    city = models.ForeignKey(City,on_delete=models.RESTRICT)
    user = models.ForeignKey(CustomUser,on_delete=models.RESTRICT)
    def __str__(self):
        return str(self.id)

class Returntimes(models.Model):
    city = models.ForeignKey(City,on_delete=models.RESTRICT)
    y1 = models.DecimalField(max_digits=5,decimal_places=2)
    y2 = models.DecimalField(max_digits=5,decimal_places=2)
    y5 = models.DecimalField(max_digits=5,decimal_places=2)
    y10 = models.DecimalField(max_digits=5,decimal_places=2)
    y20 = models.DecimalField(max_digits=5,decimal_places=2)
    y50 = models.DecimalField(max_digits=5,decimal_places=2)
    y100 = models.DecimalField(max_digits=5,decimal_places=2)
    y200 = models.DecimalField(max_digits=5,decimal_places=2)
    y500 = models.DecimalField(max_digits=5,decimal_places=2)
    y1000 = models.DecimalField(max_digits=5,decimal_places=2)
    y10000 = models.DecimalField(max_digits=5,decimal_places=2)
    y100000 = models.DecimalField(max_digits=5,decimal_places=2)
    y1000000 = models.DecimalField(max_digits=5,decimal_places=2)
    description = models.TextField(blank=True,null=True)
    def __str__(self):
        return str(self.id)

objects/templates/stad/criteria.html
{% extends 'base.html' %}

{% block content %}
<div class="columns">
  <div class="column is-one-third">
    <div class="box">
      <div class="block"><span class="tag">Framgångskriteria</span></div>
      <h3 class="title is-3">{{ criteria.name }}</h3>
      <p>{{ criteria.description }}</p>
      <a href="/edit/kriteria/{{criteria.id}}"><button class="button is-link is-small is-rounded"><i class="fa-solid fa-pen"></i>&nbsp; Ändra</button></a>
    </div>
    <a href="/handelser"><button class="button is-info is-small is-rounded"><i class="fa-solid fa-angle-left"></i>&nbsp; Tillbaka till alla händelser</button></a>




    </div>

  <div class="column is-one-third">
    <div class="box">
    <p><i class="fa-solid fa-house-flood-water"></i><b> {{ criteria.event_set.count }} oönskade händelser</b></p>
    {% for ev in criteria.event_set.all %}
    <a href="/event/{{ev.id}}">
      <div class="event_box">
        <p><b>{{ ev.name }}</b><br/> {{ ev.description}}</p>
        <div class="field is-grouped is-grouped-multiline">
          <div class="control"><div class="tags has-addons"><span class="tag is-info is-light">MALMÖ: </span><span class="tag is-info">{%if ev.returntime %}1/{{ ev.returntime }}{%else%} ej klar.{%endif%}</span></div></div>
          <div class="control"><div class="tags has-addons"><span class="tag is-info is-light">Sårbara platser: </span><span class="tag is-info">{{ ev.object_set.count }}</span></div></div>

        </div>
      </div>
    </a>
    {% endfor%}
  </div>
  </div>
  <div class="column is-one-third">
    <div class="box">
      <h2 class="title is-4">Ny oönskade händelse</h2>
      <div class="notification is-info">
      Oönskade händelser är sådant man inte vill ska hända om framgångskriterierna ska uppnås och därför ska de matcha dessa. Skriv in förslag och sortera bort de som inte är relevanta för översvämning.
      </div>


      <div class="control">
        <form method="post">
        {% csrf_token %}
        {{ form.name.name_tag }}
        {{ form.name }}
        <br/><br/>
        {{ form.description.name_tag }}
        {{ form.description }}
        <br/>
        <button class="button is-success is-fullwidth is-medium mt-5" type="submit"><i class="fa-solid fa-circle-plus"></i>&nbsp; Spara</button>
        </form>
        </div>
    </div>


    </div>
</div>
</div>

<script type="text/javascript">
  $(document).on('click', '.utv', function() {
  var id = $(this).data('id');
  if (id) {
      window.location = '/event/' + id;
  }})
  $(document).on('click', '.edt', function() {
  var id = $(this).data('id');
  if (id) {
      window.location = '/edit/event/' + id;
  }})
  function back() {
    window.location = "{{ back }}"
  }
</script>

{% endblock %}

objects/templates/stad/handlingar.html
{% extends 'base.html' %}
{% block content %}
<div class="columns">
<div class="column is-one-half">
    <div class="box">
      <h2 class="title is-2">Åtgärder</h2>
      {% for ob in city.object_set.all %}
        {% for m in ob.measure_set.all %}
        <div class="box">
          <h3 class="title is-4">{{ m.name }}</h3>
          <p>{{ m.description }}</p>
        </div>
        {% endfor %}
      {% endfor %}
      {% for ob in city.area_set.all %}
        {% for m in ob.measure_set.all %}
        <div class="cr_block">
          <h3 class="title is-4">{{ m.name }}</h3>
          <p>{{ m.description }}</p>
        </div>
        {% endfor %}
      {% endfor %}
    </div>
</div>

<div class="column is-one-half">
</div>

</div>

{% endblock %}

objects/templates/stad/strategi.html
{% extends 'base.html' %}
{% block header %}
  {% load leaflet_tags %}
  {% leaflet_css %}
  {% leaflet_js %}
{% endblock %}
{% block content %}

<div class="columns">
  <div class="column is-one-quarter">
    <div class="box">
      <small class="has-text-info">Fokusfråga </small><br/>
      <h5 class="title is-5">{{ city.focus }}</h5>
      <small class="has-text-info">Skyddsnivå</small><br/>
      <h5 class="title is-5">{{ city.level }} meter</h5>
        <small class="has-text-info">Område</small><br/>
      <div class="block">
        {% leaflet_map "specialbigmap" callback="map_init" %}
      </div>
      <small class="has-text-info">Befintliga återkomstider</small><br/>
      {% if city.returntimes_set.first.y1 > 0 %}
      <span class="tag is-success is-light">Färdiga</span>
      {% else %}
      <span class="tag is-warning is-light">Inte färdiga.</span>
      {% endif %}
      <br/><br/>
      <a href="/edit/information"><button class="button is-small is-link is-rounded"><i class="fa-solid fa-pen"></i>&nbsp; Ändra informationen</button></a>
    </div>
      <button class="js-modal-trigger button is-primary is-rounded" data-target="modal-js-example"><i class="fa-solid fa-circle-plus"></i>&nbsp; Lägg till framgångskriteria</button>
  </div>

  <div class="column">
    {% if city.criteria_set.all.count > 0 %}
    {% for cr in city.criteria_set.all %}
    <div class="box">
    <div class="columns" style="padding:0px;">
      <div class="column is-one-third">
        <p><small class="has-text-primary">Framgångskriteria</small><br/><b>{{ cr.name }}:</b>
        <small>{{ cr.description }}</small></p>
        <a href="/kriterium/{{cr.id}}"><button class="button is-small is-primary is-rounded"><i class="fa-solid fa-circle-plus"></i>&nbsp; Lägg till oönskade händelse</button></a>
      </div>
      <div class="column">
        <div style="margin-bottom:8px;"><small><i class="fa-solid fa-house-flood-water"></i> {{ cr.event_set.count }} oönskade händelser</small></div>
        {% for ev in cr.event_set.all %}
        <a href="/event/{{ev.id}}">
          <div class="event_box" style="padding:8px;">

            <div class="field is-grouped is-grouped-multiline">
              <span style="width:50%;text-align:left;"><b>{{ ev.name }}</b></span>

              <div class="control"><div class="tags has-addons"><span class="tag is-info is-light">MALMÖ: </span><span class="tag is-info">{%if ev.returntime %}1/{{ ev.returntime }}{%else%} ej klar.{%endif%}</span></div></div>
              <div class="control"><div class="tags has-addons"><span class="tag is-info is-light">Sårbara platser: </span><span class="tag is-info">{{ ev.object_set.count }}</span></div></div>

            </div>
          </div>
        </a>
        {% endfor%}
      </div>
    </div>
    </div>
    {% endfor %}
    {% endif %}

  </div>


<div id="modal-js-example" class="modal">
  <div class="modal-background"></div>

  <div class="modal-content">
    <div class="box">
      <h2 class="title is-4">Definiera framgångskriteria</h2>
      <div class="notification is-info"><p>Framgångskriterier är konkreta påståenden om vilka förhållanden som ska infrias för att utvecklingen av området ska uppfylla kriterierna i fokusfrågan.</p></div>
      <div class="control">
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
            type="submit">Spara
        </button>
        </form>
      </div>
    </div>
  </div>

  <button class="modal-close is-large" aria-label="close"></button>
</div>


<script type="text/javascript">

    $(document).on('click', '.evt', function() {
    var id = $(this).data('id');
    if (id) {
        window.location = '/event/' + id;
    }})

      function map_init(map, options) {
          // get point lat and lon
          // zoom to point & add it to map
          var basemaps = {
            'Nu '       : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '10', format: 'image/png', transparent: true, opacity: 0.5}),
            '1 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '8', format: 'image/png', transparent: true, opacity: 0.5}),
            '1.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '7', format: 'image/png', transparent: true, opacity: 0.5}),
            '2 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '6', format: 'image/png', transparent: true, opacity: 0.5}),
            '2.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '5', format: 'image/png', transparent: true, opacity: 0.5}),
            '3 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '4', format: 'image/png', transparent: true, opacity: 0.5}),
            '3.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '3', format: 'image/png', transparent: true, opacity: 0.5}),
            '4 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '2', format: 'image/png', transparent: true, opacity: 0.5}),
            '4.5 meter' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '1', format: 'image/png', transparent: true, opacity: 0.5}),
            '5 meter  ' : L.tileLayer.wms('https://gisapp.msb.se/arcgis/services/Oversvamningskarteringar/kustoversvamning/MapServer/WmsServer', { layers: '0', format: 'image/png', transparent: true, opacity: 0.5})
          }
          L.control.layers(basemaps).addTo(map);
          var group = new L.featureGroup();
          var lon = "{{ city.location.x }}";
          var lat = "{{ city.location.y }}";
          // zoom to point & add it to map
          map.setView([lat, lon], 14);
          {% if city.area %}
          var jsonob = {% autoescape off %}{{ city.get_location }}{% endautoescape %};
          var latlngs = jsonob.coordinates[0];
          var reversed = []
          function reverseFunction(value, index, array) {
              reversed += array[index].reverse();
            }
          latlngs.forEach(reverseFunction);
          var polygon = L.polygon(latlngs, {color: 'red'}).addTo(map);
          group.addLayer(polygon);
          map.fitBounds(group.getBounds());
          {% endif %}
      }
      document.addEventListener('DOMContentLoaded', () => {
  // Functions to open and close a modal
  function openModal($el) {
    $el.classList.add('is-active');
  }

  function closeModal($el) {
    $el.classList.remove('is-active');
  }

  function closeAllModals() {
    (document.querySelectorAll('.modal') || []).forEach(($modal) => {
      closeModal($modal);
    });
  }

  // Add a click event on buttons to open a specific modal
  (document.querySelectorAll('.js-modal-trigger') || []).forEach(($trigger) => {
    const modal = $trigger.dataset.target;
    const $target = document.getElementById(modal);

    $trigger.addEventListener('click', () => {
      openModal($target);
    });
  });

  // Add a click event on various child elements to close the parent modal
  (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button') || []).forEach(($close) => {
    const $target = $close.closest('.modal');

    $close.addEventListener('click', () => {
      closeModal($target);
    });
  });

  // Add a keyboard event to close all modals
  document.addEventListener('keydown', (event) => {
    const e = event || window.event;

    if (e.keyCode === 27) { // Escape key
      closeAllModals();
    }
  });
});
  </script>

{% endblock %}

objects/templates/stad/w1b.html
{% extends 'base.html' %}
{% block header %}
  {% load leaflet_tags %}
  {% leaflet_css %}
  {% leaflet_js %}
{% endblock %}
{% block content %}

<div class="columns">

  <div class="column is-one-third">
    <h3 class="title is-3">Workshop 1B</h3>
    <div class="box">
      <h2 class="title is-4">1. Definiera framgångskriterier</h2>
      <div class="notification is-info"><p>Framgångskriterier är konkreta påståenden om vilka förhållanden som ska infrias för att utvecklingen av området ska uppfylla kriterierna i fokusfrågan.</p></div>
      <div class="control">
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5"
            type="submit">Spara
        </button>
        </form>
      </div>
    </div>

    <div class="box">
      <h2 class="title is-4">2. Identifiera oönskade händelser</h2>
      <div class="notification is-info">
         Oönskade händelser är sådant man inte vill ska hända om framgångskriterierna ska uppnås och därför ska de matcha dessa. Gå igenom alla framgångskriterier och tryck på "utveckla". Skriv in förslagen som är relevanta för översvämning.
      </div>
    </div>
    <a href="/workshop1C"><button class="button is-primary is-rounded is-right">Nästa</button></a>
  </div>

<div class="column">
    <h3 class="title is-3">&nbsp;&nbsp;</h3>
  <div class="box">
    <h4 class="title is-4">Framgångskriterier</h4>
    <div class="notification"><p>Fokusfrågan: <i> {{ city.focus }}</i></p></div>

    <p></p>

    {% for cr in city.criteria_set.all %}
    <div class="box">

      <p><b>{{ cr.name }}</b></p>
      <p>{{ cr.description }}</p>
      <button class="button is-small is-primary is-rounded utv" data-id="{{ cr.id }}">Utveckla</button>
      <button class="button is-small is-link is-rounded edt" data-id="{{ cr.id }}">Ändra</button>
    </div>
    {% endfor %}

  </div>
</div>


</div>

<script type="text/javascript">

    function map_init(map, options) {
        // get point lat and lon
        var lon = "{{ city.location.x }}";
        var lat = "{{ city.location.y }}";
        // zoom to point & add it to map
        map.setView([lat, lon], 14);
    }

    $(document).on('click', '.utv', function() {
    var id = $(this).data('id');
    if (id) {
        window.location = '/kriterium/' + id;
    }})

    $(document).on('click', '.edt', function() {
    var id = $(this).data('id');
    if (id) {
        window.location = '/edit/kriteria/' + id;
    }})


  </script>

{% endblock %}

objects/templates/stad/w2.html
{% extends 'base.html' %}

{% block content %}
<div class="columns">

  <div class="column is-one-third">
  <h3 class="title is-3">Workshop 2</h3>
  <div class="box">
    <p>Navigera genom alla skapade oönskade händelser och komplettera med följande uppgifter:</p>
    <div class="notification is-info">
    <h4 class="title is-4">2A. MALMÖ</h4>
    <p>Uppgift 1 är att definiera den Minsta Acceptabla tidsLängd Mellan Översvämningar (MALMÖ) för alla oönskade händelser, det vill säga hur ofta det är acceptabelt att en oönskad händelse inträffar.</p>
    </div>
    <div class="notification is-success">
    <h4 class="title is-4">2B. Sårbara platser</h4>
    <p>Uppgift 2 är att specificera sårbara platser (objekt eller ytor) för respektive oönskad händelse och identifiera deras höjd över havet.
    </div>
    <div class="notification is-primary">
    <h4 class="title is-4">2C. Åtgärder</h4>
    <p>Uppgift 3 är att definiera åtgärder för varje sårbar plats. Alternativt kan generella åtgärder skapas som fungerar för hela området.</p>
    </div>
    <a href="/ny_atgard"><button class="button is-info is-rounded">Skapa generell åtgärd</button></a>
    </div>
  </div>

  <div class="column">
    <h3 class="title is-3">&nbsp;</h3>
  <div class="box">
    <h2 class="title is-4">Oönskade händelser</h2>
    {% for ev in city.event_set.all %}
      <div class="box">
        <p><b>{{ ev.name }}</b></p><p>{{ ev.description }}</p>
        <p>Framgångskriteria: <span class="tag">{{ ev.criteria.name }}</span></p>
        <p>MALMÖ: <span class="tag">{%if ev.returntime %}1/{{ ev.returntime }}{%else%} ej klar.{%endif%}</span>  Sårbara platser: <span class="tag">{{ ev.object_set.count }}</span></p>
        <button class="button is-small is-primary is-rounded utv" data-id="{{ ev.id }}">Utveckla</button>
        <button class="button is-small is-link is-rounded edt" data-id="{{ ev.id }}">Ändra</button>
      </div>
    {% endfor %}
  </div>
  </div>
</div>

<script type="text/javascript">

    $(document).on('click', '.utv', function() {
    var id = $(this).data('id');
    if (id) {
        window.location = '/event/' + id;
    }})
    $(document).on('click', '.edt', function() {
    var id = $(this).data('id');
    if (id) {
        window.location = '/edit/event/' + id;
    }})
  </script>


{% endblock %}